# Declare your hostname before running docker-compose
# $ export M2SETUP_PROJECT=myproject
version: "2"
services:
  varnish:
    build:
      context: varnish/
    environment:
    - VIRTUAL_HOST=${M2SETUP_VIRTUAL_HOST}
    - VIRTUAL_PORT=80
    - HTTPS_METHOD=redirect
    ports:
    - '${M2SETUP_PORT_80}:80'
    links:
    - web

  web:
    build:
      context: nginx/
    ports:
    - '${M2SETUP_PORT_443}:443'
    - 80
    links:
    - fpm
    - db
    volumes_from:
    - appdata
    env_file:
    - global.env
    environment:
    - VIRTUAL_HOST=${M2SETUP_PROJECT}
    - VIRTUAL_PORT=80
    - HTTPS_METHOD=redirect

  fpm:
    hostname: fpm.${M2SETUP_PROJECT}
    build:
      context: 7.2-fpm/
    ports:
    - 9000
    links:
    - db
    volumes_from:
    - appdata
    env_file:
    - global.env

  db:
    image: mariadb:10
    ports:
    - 3306
    volumes_from:
    - dbdata
    environment:
    - MYSQL_ROOT_PASSWORD=magento2
    - MYSQL_DATABASE=magento2
    - MYSQL_USER=magento2
    - MYSQL_PASSWORD=magento2

  cli:
    hostname: cli.${M2SETUP_PROJECT}
    build:
      context: 7.2-cli/
    links:
    - db
    volumes:
    - ~/.composer/cache:/root/.composer/cache
    volumes_from:
    - appdata
    env_file:
    - global.env
    - ./composer.env
    environment:
    - M2SETUP_INSTALL_DB=true
    - M2SETUP_DB_HOST=db
    - M2SETUP_DB_NAME=magento2
    - M2SETUP_DB_USER=magento2
    - M2SETUP_DB_PASSWORD=magento2
    - M2SETUP_BASE_URL=http://${M2SETUP_VIRTUAL_HOST}/
    - M2SETUP_SECURE_BASE_URL=https://${M2SETUP_VIRTUAL_HOST}/
    - M2SETUP_BACKEND_FRONTNAME=admin
    - M2SETUP_ADMIN_FIRSTNAME=Admin
    - M2SETUP_ADMIN_LASTNAME=User
    - M2SETUP_ADMIN_EMAIL=admin@example.com
    - M2SETUP_ADMIN_USER=admin
    - M2SETUP_ADMIN_PASSWORD=qweqwe1
    - M2SETUP_VERSION=2.3
    #- M2SETUP_USE_SAMPLE_DATA=false
    - M2SETUP_PROJECT_TYPE=community

  cron:
    build:
      context: 7.2-cli/
    hostname: cron.${M2SETUP_PROJECT}
    command: run-cron
    environment:
    - ENABLE_SENDMAIL=true
    volumes_from:
    - appdata
    links:
    - db

  appdata:
    image: tianon/true
    volumes:
    - ./magento:/var/www/magento

  dbdata:
    image: tianon/true
    volumes:
    - /var/lib/mysql
